### ISSUE TITLE
Več poštnih številk :)

### ISSUE THREAD

**Issue by pogla** [Jurero123/woo-postne-stevilke#1]
[Tukaj](https://sl.wikipedia.org/wiki/Seznam_po%C5%A1tnih_%C5%A1tevilk_v_Sloveniji) je podrobnejši seznam poštnih številk. Recimo 1107 Šiška...

Čudno pa mi je, da nikjer ne najdem recimo 1108 ljubljana.

**Comment by Jurero123** [comment]
Tnx, sem naknadno uporabil "uradni" seznam na spodnji povezavi:
https://www.posta.si/zasebno-site/Documents/Seznami/Seznam%20po%C5%A1tnih%20%C5%A1tevilk%20za%20naslavljanje.pdf
